#!/usr/bin/perl
use strict;
use warnings;
use CHI;
my $cache = CHI->new( driver => 'File', root_dir => '_cache' );

my $filename = "changedetection.account";
open my $F, $filename or die "Could not open file '$filename': $!";

chomp(my $email = <$F>);
my $key = "monitors:$email";
$cache->remove($key);
