#!/usr/bin/perl

use strict;
use Tratten::Monitored;

print "{| border='1' cellspacing='0' class='wikitable sortable'\n! tratten link !! summary !! log file\n";

for (sort keys %Tratten::Monitored::refnum) {
  my %x = %{ $Tratten::Monitored::refnum{$_} };
  print "|-\n| [[$_]] || $x{desc} || [$x{log}]\n";
}

print "|}\n";
