#! /usr/bin/perl -w

use strict;
use warnings;
use diagnostics;

use utf8;
binmode STDOUT, ":utf8";
binmode STDERR, ":utf8";

use Tratten::Monitored;
use Tratten::Cache;
use Tratten::Committee;

print "{| border='1' cellspacing='0' class='wikitable sortable'\n! tratten link !! summary";
print " !! $_" for @Tratten::Committee::abbr;
print "\n";

for (sort keys %Tratten::Monitored::refnum) {
  my %index = ();
  my %doss = %{ Tratten::Monitored::dossier($_) || next };
  my %monitor = %{ $doss{monitor} };
  print STDERR "WARNING: Monitored page $monitor{log} is $doss{reference} but is named $monitor{refnum}!\n" if $monitor{refnum} ne $doss{reference};
  print "|-\n | [[$doss{reference}]] || $monitor{desc}";

  for (@{$doss{agents}}) {
    $_->{committee} =~ /^(.+?)\s+\((.+)\)$/ or die;
    my ($comm, $status) = ($1, $2);
    my $abbr = Tratten::Committee::abbreviate($comm) or next;
    $index{$abbr} = [($_->{MEP}||""), $status];
  }
  for (@Tratten::Committee::abbr) {
    if (defined $index{$_}) {
      my ($MEP, $status) = @{ $index{$_} };
      print " || ($status) $MEP";
    }
    else { print " ||" }
  }
  print "\n";
  print STDERR "$monitor{uri} $doss{reference}: ". (scalar keys %index) ."\n";
}

print "|}\n";
