#!/usr/bin/perl

use strict;

open my $F, "changedetection.account" or die;

chomp(my $email = <$F>);
chomp(my $password = <$F>);

my $args = "-# --cookie cookies --cookie-jar cookies";
my $form = "-F 'email=$email' -F 'frompage=http://www.changedetection.com/monitors.html' -F 'login=log in' -F 'op=login' -F 'pw=$password'";

`curl $args --url http://www.changedetection.com/index.html`;
$_ = `curl $args $form -L --url http://www.changedetection.com/login.html`;

print "{| border='1' cellspacing='0' class='wikitable sortable'\n! tratten link !! summary !! log file\n";

my @matches = /<a href="\/log\/[^"]+" title="[^"]+"/g;
for (@matches) {
  /href="([^"]+)" title="([^ ]+)\s+([^"]+)/ or die;
  print "|-\n| [[$2]] || $3 || [http://www.changedetection.com$1]\n";
}

print "|}\n";
