#!/usr/bin/perl
use strict;
use warnings;
use Tratten::Dossier;
use Tratten::Monitored;
use Tratten::Committee;

binmode STDOUT, ":utf8";

my $uri = $ARGV[0];
my $dossier;

if ($Tratten::Monitored::uri{$uri}) { $dossier = &Tratten::Monitored::dossier($uri); }
else {
  my $page = &Tratten::Cache::URI($uri, expire_if => sub { time - $_[0]->{timestamp} > 10000 });
  $dossier = Tratten::Dossier::parse($page);
}

my %comm;
my $lead;

for (@{ $dossier->{agents} }) {
  $_->{committee} =~ /^(.+?)\s+\((.+)\)$/ or die;
  my ($comm, $status) = ($1, $2);
  my $abbr = Tratten::Committee::abbreviate($comm) or die;
  if ($status eq "responsible") { die if $lead; $lead = $abbr; }
  $comm{$abbr} = $_->{MEP};
}

print "<big><big>'''", $dossier->{title}, "'''</big></big>";
if ($dossier->{monitor}) { print " [", $dossier->{monitor}->{log}, " change log]"; }
print " [$uri oeil]";
{
  local $_ = $dossier->{title}; s/\s/+/g;
  print " [http://www.google.com/search?q=$_ google]";
}
print "\n";
for (@{ $dossier->{forecasts} }) {
  print "<br/>'''";
  my $date = $_->{date};
  if ($date =~ m#^(\d\d)/(\d\d)/(\d\d\d\d)$#) { $date = "$3-$2-$1"; }
  print $date, "''' ", $_->{activity}, "\n";
}
print "{| border='1' cellspacing='0' class='wikitable sortable'\n";
print "! Function";
for (sort keys %comm) { print " !! [[", $dossier->{reference}, "/$_|$_]]"; }
print "\n|-\n| EP MEP rapporteur (lead)";
for (sort keys %comm) { print " || ", ($_ eq $lead) ? $comm{$_} : "-"; }
print "\n|-\n| EP MEP shadow rapporteur(s) (opinion)";
for (sort keys %comm) { print " || ", ($_ ne $lead) ? $comm{$_} : "-"; }
print "\n|}\n";
