#!/usr/bin/perl

use strict;
#use warnings;

open OUT, ">out.txt";

our $table_header = "{| border='1' cellspacing='0' class='wikitable sortable'
! oeil link / tratten page !! stage reached !! procedure !! stage !! name !! committee !! rapporteur !! COM number !! monitored\n";
our $table_footer = "|}\n";

our @stageId = (100, 210, 235, 290, 300, 400, 500, 600, 610, 640, 700, 710, 720);

our %monitored;

sub get_monitored {
  open my $F, "changedetection.account";

  chomp(my $email = <$F>);
  chomp(my $password = <$F>);

  my $args = "-# --cookie cookies --cookie-jar cookies";
  my $form = "-F 'email=$email' -F 'frompage=http://www.changedetection.com/monitors.html' -F 'login=log in' -F 'op=login' -F 'pw=$password'";

  print "Logging in to changedetection...\n";
  `curl $args --url http://www.changedetection.com/index.html`;
  $_ = `curl $args $form -L --url http://www.changedetection.com/login.html`;

  my @matches = /<a href="\/log\/[^"]+" title="[^"]+"/g;
  for (@matches) {
    /href="([^"]+)" title="([^ ]+)/ or die;
    $monitored{$2} = "http://www.changedetection.com$1";
  }
  my $number_monitored = keys %monitored;
  print "$number_monitored pages are monitored.\n";
}

our $stageId;
our $next_index;
our $number_results;
our $stage_reached;

sub get_page {
  my $form = "-d 'xpath=/oeil/search/procstage/stage' -d 'scope=stage' -d 'countEStat=true' -d 'startIndex=$next_index' -d 'stageId=$stageId' -d 'pageSize=50'";
  my @body = `curl -# $form --url http://www.europarl.europa.eu/oeil/FindByStage.do`;
  while (@body) {
    $_ = shift @body;
    if (/<span class="number_results">(\d+)<\/span>/) {
      $number_results = $1;
      shift @body;
      shift @body;
      ($stage_reached = shift @body) =~ s/^\s*(.+)\s*$/$1/;
      last;
    }
  }
  $next_index += 50;
  return @body;
}

  
our @data;

sub next_bare { while (@data) { $_ = shift @data; return $1 if /^\s*(\w.*)$/; } }

sub table_body {
  while (@data) {
    $_ = shift @data;
    if (/(file\.jsp\?id=[0-9]+)" class="com_acronym">([^<]+)<\/a>/) {
      my $url = "http://www.europarl.europa.eu/oeil/$1";
      my $id = $2;
      my ($name, $proc, $stage, $committee, $rapporteur, $com) = ();
      while (@data) {
        $_ = shift @data;
        last if /procedure number/;
        ($proc, $stage) = ($1,$3) if /">([^<,]+)(, ([^<]+))?<\/div>/;
        $name = &next_bare if /starts with the title/;
        $committee = &next_bare if /Display the committee responsible/;
        $rapporteur = &next_bare if /Display the reporter or co-reporter/;
        $com = $1 if /(COM\(\d+\)\d+)/;
      }
      my $monitored = "[" . $monitored{$id} . " $1]" if $monitored{$id} =~ /\/([^\/]+)\.html$/;
      print OUT "|-\n";
      print OUT "| [$url $id] / [[$id]] || $stage_reached || $proc || $stage || $name || $committee || $rapporteur || $com || $monitored\n";
    }
  }
}

&get_monitored;

print "Getting oeil-pages...\n";
print OUT $table_header;
while (@stageId) {
  $stageId = shift @stageId;
  $next_index = 1;
  $number_results = 1;
  while ($next_index <= $number_results) {
    @data = &get_page;
    &table_body;
    print "Waiting 3 seconds between pages for courtesy.\n";
    sleep 3;
  }
}
print OUT $table_footer;

print "Done.\n";
