#!/usr/bin/perl

$infile = shift;
open IN, $infile;
open OUT, ">out.txt";

sub next_bare { while (<IN>) { return $1 if /^\s*(\w.*)$/; } }

print OUT "{| border='1' cellspacing='0' class='wikitable sortable'
! oeil link / tratten page !! procedure !! stage !! name !! committee !! rapporteur !! COM number !! comments\n";

while (<IN>) {
  if (/(file\.jsp\?id=[0-9]+)" class="com_acronym">([^<]+)<\/a>/) {
    $url = "http://www.europarl.europa.eu/oeil/$1";
    $id = $2;
    ($name, $proc, $stage, $committee, $rapporteur, $com) = ();
    while (<IN>) {
      last if /procedure number/;
      ($proc, $stage) = ($1,$3) if /">([^<,]+)(, ([^<]+))?<\/div>/;
      $name = &next_bare if /starts with the title/;
      $committee = &next_bare if /Display the committee responsible/;
      $rapporteur = &next_bare if /Display the reporter or co-reporter/;
      $com = $1 if /(COM\(\d+\)\d+)/;
    }
    print OUT "|-\n";
    print OUT "| [$url $id] / [[$id]] || $proc || $stage || $name || $committee || $rapporteur || $com || \n";
  }
}

print OUT "|}\n";
